<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.X5.Ou00' shared service.

return $this->privates['.service_locator.X5.Ou00'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\Admin\\AdminPropertyController::delete' => ['privates', '.service_locator.N38ovWA', 'get_ServiceLocator_N38ovWAService.php', true],
    'App\\Controller\\Admin\\AdminPropertyController::index' => ['privates', '.service_locator.x6NL76h', 'get_ServiceLocator_X6NL76hService.php', true],
    'App\\Controller\\PropertyController::show_product' => ['privates', '.service_locator.mX7rmQ1', 'get_ServiceLocator_MX7rmQ1Service.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\Admin\\AdminPropertyController:delete' => ['privates', '.service_locator.N38ovWA', 'get_ServiceLocator_N38ovWAService.php', true],
    'App\\Controller\\Admin\\AdminPropertyController:index' => ['privates', '.service_locator.x6NL76h', 'get_ServiceLocator_X6NL76hService.php', true],
    'App\\Controller\\PropertyController:show_product' => ['privates', '.service_locator.mX7rmQ1', 'get_ServiceLocator_MX7rmQ1Service.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
], [
    'App\\Controller\\Admin\\AdminPropertyController::delete' => '?',
    'App\\Controller\\Admin\\AdminPropertyController::index' => '?',
    'App\\Controller\\PropertyController::show_product' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\Admin\\AdminPropertyController:delete' => '?',
    'App\\Controller\\Admin\\AdminPropertyController:index' => '?',
    'App\\Controller\\PropertyController:show_product' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
