<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBjqSC1d\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBjqSC1d/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBjqSC1d.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBjqSC1d\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBjqSC1d\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BjqSC1d',
    'container.build_id' => '4c7c709c',
    'container.build_time' => 1571322359,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBjqSC1d');
